.TH "src/utils/gsl_complex_utils.h" 3 "Mon Mar 29 2021" "Version 1" "PArticle Wake ANalysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/gsl_complex_utils.h \- GNU Scientific Library Complex Matrix/Vector utilities for PAWAN\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gsl_utils\&.h'\fP
.br
\fC#include <gsl/gsl_complex\&.h>\fP
.br
\fC#include <gsl/gsl_complex_math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDISP\fP (std::string s, const gsl_complex &c, std::ostream &os=std::cout)"
.br
.RI "Print string and complex number\&. "
.ti -1c
.RI "void \fBDISP\fP (std::string s, const gsl_vector_complex *v, std::ostream &os=std::cout)"
.br
.RI "Print string and long complex array of values\&. "
.ti -1c
.RI "void \fBDISP\fP (std::string s, const gsl_matrix_complex *m, std::ostream &os=std::cout)"
.br
.RI "Print string and matrix of complex values\&. "
.ti -1c
.RI "void \fBconjugate_gsl_vector\fP (const gsl_vector_complex *V, gsl_vector_complex *A)"
.br
.RI "Find the conjugate of a gsl vector\&. "
.ti -1c
.RI "void \fBcomplex_vector_product\fP (const gsl_complex &C, const double D[3], gsl_vector_complex *A)"
.br
.RI "Complex number multiplied with Double vector\&. "
.ti -1c
.RI "void \fBflip_sign\fP (gsl_vector_complex *A)"
.br
.RI "Flip sign of complex number vector\&. "
.ti -1c
.RI "void \fBgsl_vector_complex_mul_real\fP (const double &r, gsl_vector_complex *A)"
.br
.RI "Multiply complex vector with real number\&. "
.ti -1c
.RI "void \fBgsl_vector_complex_div_real\fP (const double &r, gsl_vector_complex *A)"
.br
.RI "Multiply complex vector with real number\&. "
.ti -1c
.RI "void \fBgsl_real_to_complex_vector\fP (gsl_vector *real, gsl_vector_complex *comp)"
.br
.RI "Create complex vector from real vector\&. "
.ti -1c
.RI "void \fBgsl_conjugate_vector\fP (gsl_vector_complex *A, gsl_vector_complex *B)"
.br
.RI "Conjugate complex vector\&. "
.in -1c
.SH "Detailed Description"
.PP 
GNU Scientific Library Complex Matrix/Vector utilities for PAWAN\&. 

PArticle Wake ANalysis
.PP
\fBAuthor\fP
.RS 4
Puneet Singh 
.RE
.PP
\fBDate\fP
.RS 4
03/28/2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void complex_vector_product (const gsl_complex & C, const double D[3], gsl_vector_complex * A)\fC [inline]\fP"

.PP
Complex number multiplied with Double vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIC\fP complex number 
.br
\fID\fP double vector 
.br
\fIA\fP output complex vector Returns Z = complex vector 
.RE
.PP

.SS "void conjugate_gsl_vector (const gsl_vector_complex * V, gsl_vector_complex * A)\fC [inline]\fP"

.PP
Find the conjugate of a gsl vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIV\fP gsl vector 
.br
\fIA\fP output vector 
.RE
.PP

.SS "void DISP (std::string s, const gsl_complex & c, std::ostream & os = \fCstd::cout\fP)\fC [inline]\fP"

.PP
Print string and complex number\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP String 
.br
\fIc\fP Complex number 
.br
\fIos\fP Output stream 
.RE
.PP

.SS "void DISP (std::string s, const gsl_matrix_complex * m, std::ostream & os = \fCstd::cout\fP)\fC [inline]\fP"

.PP
Print string and matrix of complex values\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP String 
.br
\fIm\fP gsl matrix 
.br
\fIos\fP Output stream 
.RE
.PP

.SS "void DISP (std::string s, const gsl_vector_complex * v, std::ostream & os = \fCstd::cout\fP)\fC [inline]\fP"

.PP
Print string and long complex array of values\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP String 
.br
\fIv\fP gsl complex vector 
.br
\fIos\fP Output stream 
.RE
.PP

.SS "void flip_sign (gsl_vector_complex * A)\fC [inline]\fP"

.PP
Flip sign of complex number vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIA\fP complex number vector 
.RE
.PP

.SS "void gsl_conjugate_vector (gsl_vector_complex * A, gsl_vector_complex * B)\fC [inline]\fP"

.PP
Conjugate complex vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIA\fP conjugate complex number vector 
.br
\fIB\fP original complex number vector 
.RE
.PP

.SS "void gsl_real_to_complex_vector (gsl_vector * real, gsl_vector_complex * comp)\fC [inline]\fP"

.PP
Create complex vector from real vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIreal\fP Real number vector 
.br
\fIcomp\fP Complex number vector 
.RE
.PP

.SS "void gsl_vector_complex_div_real (const double & r, gsl_vector_complex * A)\fC [inline]\fP"

.PP
Multiply complex vector with real number\&. 
.PP
\fBParameters\fP
.RS 4
\fIr\fP real number 
.br
\fIA\fP complex number vector 
.RE
.PP

.SS "void gsl_vector_complex_mul_real (const double & r, gsl_vector_complex * A)\fC [inline]\fP"

.PP
Multiply complex vector with real number\&. 
.PP
\fBParameters\fP
.RS 4
\fIr\fP real number 
.br
\fIA\fP complex number vector 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PArticle Wake ANalysis from the source code\&.
