.TH "src/wake/wake.cpp" 3 "Mon Mar 29 2021" "Version 1" "PArticle Wake ANalysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wake/wake.cpp \- Routines for Wake calculations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wake\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Routines for Wake calculations\&. 

PArticle Wake ANalysis
.PP
\fBAuthor\fP
.RS 4
Puneet Singh 
.RE
.PP
\fBDate\fP
.RS 4
03/28/2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PArticle Wake ANalysis from the source code\&.
