.TH "src/wake/wake.h" 3 "Mon Mar 29 2021" "Version 1" "PArticle Wake ANalysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wake/wake.h \- Header for WAKE lass\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <gsl/gsl_math\&.h>\fP
.br
\fC#include <gsl/gsl_matrix\&.h>\fP
.br
\fC#include 'src/utils/gsl_utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__wake\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for WAKE lass\&. 

PArticle Wake ANalysis
.PP
\fBAuthor\fP
.RS 4
Puneet Singh 
.RE
.PP
\fBDate\fP
.RS 4
03/28/2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PArticle Wake ANalysis from the source code\&.
